version: '3.8'

services:
  linux-config-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linux-config-installer-test
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - NONINTERACTIVE=1
    volumes:
      - ./install-deps.sh:/home/testuser/install-deps.sh:ro
    command: >
      bash -c "
        echo '=== Starting installation test ===' &&
        ./install-deps.sh &&
        echo '=== Verifying installations ===' &&
        curl --version &&
        brew --version &&
        nvim --version &&
        tmux -V &&
        zig version &&
        git --version &&
        fzf --version &&
        lazygit --version &&
        rg --version &&
        docker --version &&
        echo '=== Test completed successfully ==='
      "
    networks:
      - test-network

networks:
  test-network:
    driver: bridge